### ISSUE TITLE
Inquiry about future of the plugin

### ISSUE THREAD

**Issue by zoccoler** [jdeschamps/napari-sklearn-decomposition#10]
Hi guys, I hope you are doing well!

I have been working on a new plugin which relies a lot on sklearn-decomposition, but I am aiming it to be a more practical decomposition plugin, for example, introducing label layers and time plots.

Since I intend on building it on top of the structure of this one, I wanted to know your opinion about it to make a decision. What would be more interesting for you? @jdeschamps @guiwitz @psobolewskiPhD 

1. Push changes here and modify this one (including its name)
2. Keep this one as it is and fork it to work on a separate project

In case of the second option, of course you are welcome to join if you like, just send me a message later 😃  

Best,
Marcelo

**Comment by guiwitz** [comment]
Hi @zoccoler,

given that little development is happening here and that I don't think anybody crucially depends on this plugin, both solutions are fine with me. If you decide to heavily modify the current repo, maybe it's a good idea if the repo is transferred to you? May I also ask what type of application you have in mind for an "extended" plugin?

Cheers,
Guillaume

**Comment by psobolewskiPhD** [comment]
@zoccoler I second what @guiwitz wrote. 
Do whatever is easiest; I don't think this plugin at the moment does anything spectacularly practical, nor is it released, so I doubt anyone will mind—or even notice—changes.

**Comment by zoccoler** [comment]
Hi @guiwitz  and @psobolewskiPhD ,

Thanks for the feedback! I could then move it to my account if @jdeschamps agrees. I intend to let the current functionalities there anyway and I would consider myself more responsible for maintaining it.

So I was thinking of having it available to decompose timelapse data. I know there are a couple softwares that use these techniques to identify overlapping firing neurons for example. I don't know how useful it could be to other types of data, but I thought at least bringing this to napari could stimulate new possibilities 🚀

**Comment by zoccoler** [comment]
Hey guys, 
so for now I will be forking because I want to add an stICA implementation which is not just a single corresponding function from sklearn and keeping this name from now on won't make much sense in my opinion. I'll indicate the link here soon!

**Comment by jdeschamps** [comment]
Hey @zoccoler ! Sorry my gh notifications are not really on point.

Whatever is easier for you! But I think a good solution is for me to transfer the ownership to you, that way everything is a bit cleaner, especially if you build on top. :)

I am too swamped to contribute anything :/

**Comment by zoccoler** [comment]
Ok cool! Thanks @jdeschamps !  :) After that, I will bring changes to this one then.

**Comment by jdeschamps** [comment]
You would need to delete the fork on your github repo first, so I can transfer it!

**Comment by zoccoler** [comment]
Interesting, OK, I just did it.

**Comment by jdeschamps** [comment]
You should have received a notification :)

**Comment by zoccoler** [comment]
Thanks a lot! :D
