### ISSUE TITLE
Choice of method after default (PCA) doesn't work (image greyed out)

### ISSUE THREAD

**Issue by psobolewskiPhD** [jdeschamps/napari-sklearn-decomposition#4]
I mentioned this in the PR that's been merged and closed:
https://github.com/jdeschamps/napari-sklearn-decomposition/pull/2
So posting as an issue so we don't lose track of it totally.
Basically, if you try to change the decomposition method from the default (PCA at the moment) then the `image` dropdown is greyed out.
Going back to PCA also doesn't work.
But delete and reopen the sample Faces and the new choice works.
So I guess when the new widget is appended it doesn't inherit the layers list and that list needs to be modified to trigger the magicgui magic that makes the list.

**Comment by jdeschamps** [comment]
If I am not mistaken, then we would have to do something like this: https://github.com/pattonw/napari-affinities/blob/7d9eab9100daf607ce7351f8717bff37ad71acf0/src/napari_affinities/widget.py#L61

**Comment by psobolewskiPhD** [comment]
You're absolutely right!
Worked perfectly, PR inc.

**Comment by jdeschamps** [comment]
Perfect! Is there still a problem when the images are added before the plugin is loaded? I know that I am facing this on another plugin.

I am on holidays but can try when back.

**Comment by psobolewskiPhD** [comment]
I've always opened the images then the plugin...
I can confirm: 
Open Sample then Open the plugin via plugins menu and everything is functional.
I don't have another dataset handy to test, but seems fine. Will close this issue. If it pops up, we can make a new issue and then (hopefully) PR.
